### ISSUE TITLE
Duplicated tileset causing rendering issues

### ISSUE THREAD

**Issue by BWPanda** [Zukero/andors-trail#117]
I have been writing some code to render maps from TMX files, and all seems to be working well. However I noticed a problem with one of the maps (blackwater_mountain7) and I think it's to do with a duplicated tileset in the TMX file: https://github.com/Zukero/andors-trail/blob/master/AndorsTrail/res/xml/blackwater_mountain7.tmx#L138

Not only does the image source path look weird compared to the rest, but that exact same tileset is also defined earlier in the same TMX file...

**Comment by BWPanda** [comment]
And the same with 'wild20a': https://github.com/Zukero/andors-trail/blob/master/AndorsTrail/res/xml/wild20a.tmx#L186

**Comment by Zukero** [comment]
Indeed. I just checked and there was no impact on removing these lines. I just pushed the corrected ones.
