### ISSUE TITLE
Night Visit Quest - Missing dialog option

### ISSUE THREAD

**Issue by malnvenshorn** [Zukero/andors-trail#122]
It seems that I cannot complete the given quest. I talked to the warden and informed him about the plan of the thieves and he asks me to give them false information, but it seems there is no branch in the dialog with Ferrik to actually give him the misinformation. Is it a bug or do I miss something? :thinking:

**Comment by Rijackson** [comment]
Please post you question on the forums: https://andorstrail.com/

**Comment by malnvenshorn** [comment]
It seems that this has been already reported. https://www.andorstrail.com/viewtopic.php?f=3&t=5042#p58130

The bug which allows to complete the quest by simple talking to the warden again is fixed, but the dialog branch is still missing in the latest version (0.7.5)

**Comment by Rijackson** [comment]
I'll take a look. Maybe it never got fixed.

**Comment by Rijackson** [comment]
Do you have the quest step "The guard captain wants me to tell the thieves that the security will be lowered for tonight. We might be able to catch some of the thieves."?

**Comment by malnvenshorn** [comment]
Yes I have this step, but there is no option to give Ferrik the information. What I can do is accept the quest from Ferrik to give the potion to the Warden, but it's also not possible to compete this quest at this point because if I talk to the Warden I can only tell him that I'm not done with his quest yet.

**Comment by Rijackson** [comment]
OK. Do you have this step? "Farrik in the Fallhaven Thieves' Guild told me the details of the plan, and I accepted the task of helping him. The guard captain apparently has a drinking problem. The plan is that I get a prepared mead from the cook in the Thieves' Guild that will knock out the guard captain in the jail. I might be required to bribe the guard captain."

**Comment by malnvenshorn** [comment]
No, but I can still get it from Ferrik.

**Comment by Rijackson** [comment]
Thanks. You need both of those quest steps to give Farrik the misinformation. So if you don't initially agree to help the guild, you then can't give the misinformation. I'll come up with a fix.

**Comment by Rijackson** [comment]
That was a little more work to fix than I thought. It was kind of messed up. You could both tell the thieves that you would help them, and tell them that you would inform on them. I fixed that (using negated quest requirements, which I don't think were available when that quest was written). Now you get to choose one path only, and from there everything should work. See here for the fix: https://github.com/Rijackson/0_7_6_ATCS

**Comment by Rijackson** [comment]
@Zukero you should close this issue. Any further discussion should take place on the 0_7_6_ATCS repo.

**Comment by Zukero** [comment]
Okay! 👍
