### ISSUE TITLE
investigate why failed check for trailing question

### ISSUE THREAD

**Issue by leela52452** [Zukero/andors-trail#134]
both source and translation have trailing question, yet they are listed as failed checks.

https://hosted.weblate.org/translate/andors-trail/game-content/fr/?type=check:end_question
https://hosted.weblate.org/translate/andors-trail/game-content/fr_AG/?type=check:end_question

**Comment by Zukero** [comment]
My guess is that because in French, you need a space before a question mark, or any two-strokes symbol except the semicolon ";". In English, you only have a space after.

**Comment by leela52452** [comment]
added space before question mark :)
