### ISSUE TITLE
Fix the names of variables

### ISSUE THREAD

**Issue by KOLANICH** [Zukero/andors-trail#39]
https://github.com/android/platform_frameworks_base/blob/master/core/java/android/os/Parcel.java
> Parcel is not a general-purpose serialization mechanism.  This class (and the corresponding API for placing arbitrary objects into a Parcel) is designed as a high-performance IPC transport.  As such, it is not appropriate to place any Parcel data in to persistent storage: changes in the underlying implementation of any of the data in the Parcel can render older data unreadable.

**Comment by Zukero** [comment]
We're not using this class but ByteArrayOutputStream. 
Or did I miss something?

**Comment by KOLANICH** [comment]
Yes, the names "writeToParcel" make impression that parcel is used. Please fix them.

**Comment by Zukero** [comment]
Honestly, I don't see the point of refactoring the code to avoid using a
common noun that coincidentally match an existing class name of the
platform that we never use. It's a dangerously slippery and painful slope
IMHO.
