### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by uchchishta** [Zukero/andors-trail#41]
Can you tag releases so f-droid can pickup? The current version in f-droid is 3 years old. BTW, incredible game!

**Comment by Zukero** [comment]
Sadly, releases are already tagged. The last release is indeed over 3 years old (nearly 4 now).
We are hard at work to provide a new version as soon as possible, and it will be tagged for F-Droid to pick up. You can follow the project news on our forums at https://andorstrail.com/

**Comment by uchchishta** [comment]
Thank you so much!😊  I'm eager to try the new version!
