### ISSUE TITLE
Save issue in first cave

### ISSUE THREAD

**Issue by ShalokShalom** [Zukero/andors-trail#42]
Hi there :)

I saved in the first cave, in front of the huge rat.
Then, I fought with this boss, which leads me to a game death. 
I closed the application and loaded my savegame. 

I was on the same position, as when I saved the game, while the boss had the same amount of live points as when I shut down the application. 

This means, the LP of the rat hit the save game, without manually saving the game.

**Comment by Zukero** [comment]
Hello. 

Did you use the "Continue current game" button on the title screen or did you use the "Load" button?
Are you using the Google Play release version of the game? 
What device (brand,  model and Android version) do you play on?
I'll try to reproduce the issue. 

Thanks for reporting this.

**Comment by ShalokShalom** [comment]
> Did you use the "Continue current game" button on the title screen or did you use the "Load" button?

Hnn, I think I choose the first one. 

Is it possible that this gets saved automatically and I simply got placed out of the fight, which I left through the closement of the app?

>  Are you using the Google Play release version of the game?

No. F-Droid

>  What device (brand, model and Android version) do you play on?

BlackBerry Z10, Android Runtime 4.3

**Comment by Zukero** [comment]
When you use "Continue current game", you are actually loading an autosave
slot, and not your last saved game. The fact that you are playing on a BB
with android compatibility could explain the fact that the game didn't
manage to update the autosave before you closed the game.

I couldn't reproduce the issue on an android device.

Le 7 janv. 2018 12:35, "MatthiasSchuster" <notifications@github.com> a
écrit :

**Comment by ShalokShalom** [comment]
Well, it did update the savegame. 

The thing is, that it autosaved while the battle and it put my character outside of it, next to the rat. 

Once I re-entered the battle, the rat had so much energy as when I closed the game.
