### ISSUE TITLE
Barkskin - Not available at Level 12

### ISSUE THREAD

**Issue by ShalokShalom** [Zukero/andors-trail#43]
Yep. I am at level 12 and it greys the Level 10 requirement out. How to do now?

**Comment by Rijackson** [comment]
It greys out the requirements you meet, because they are not relevant. If the button for "Level up" is not greyed out, you can level up.

If you have a suspected bug, it would be better if you brought them up here: https://andorstrail.com/viewforum.php?f=3

**Comment by Zukero** [comment]
There's a second requirement for this skill. You must have at least 15 base block chance. This means that you need to affect at least five level-up bonuses to block chance.
Obviously, you also need an available skill point. 

Our forums at https://andorstrail.com are full of great advice and strategies.

**Comment by ShalokShalom** [comment]
Ah, I got it. My block chance is at 20%, while with equipment. 
For the base skills, they are not appearing at all, which means 0% probably. 
Can you tell me, why this is the case, while I activated the level 1 of the block chance skill?
It adds 9%, while obviously to the equipment costs. 
How can I increase the basic block chance?

**Comment by Zukero** [comment]
Base stats are without skills and equipments. Thus your 9% from the skill are not displayed in the base stats.

When you level up, you can choose a stat to increase:
+5 Attack Chance (AC)
+3 Block Chance (BC)
+1 Attack Damage (AD)
+5 Health Points (HP)

Choose +3 BC 5 times to have reached 15 base BC.

**Comment by ShalokShalom** [comment]
Ah, I see. Thanks a lot
