### ISSUE TITLE
Similar names with small difference

### ISSUE THREAD

**Issue by urbalazs** [Zukero/andors-trail#79]
Hello @Rijackson

I execute this command to extract the capitalized words (names expected):
`grep -ho '[A-Z][a-z][^" .,;?!*]*' AndorsTrail/res/raw/*.json | sort -u`

After a manual checking I found these names, which are similar, but only one letter differs:

- Arghes, Arghest
- Aryfola, Aryfora
- Berbane, Berbanes
- Damerialia, Damerilia, Damerilias
- Elythara, Elytharan
- Erumem, Erumen

Can you please check what are the correct names?

**Comment by urbalazs** [comment]
> Damerilias is the plural of Damerilia, so that's fine.

As I see, damerilias are "flowers that grow only in Remgard", right? We have both _Damerilias_ (with capital letter) and _damerilias_ (with lowercase letter). What is the correct?
In my opinion it should be written with lowercase letters as other flower names are written: roses, daffodils, etc.

> Erumem is the correct name, but erumen occurs only in internal IDs.

"Erume**n**" occurs not only in internal IDs, but in `monsterlist_v0611_monsters1.json` (4 times):

- Strong Erumen Lizard
- Vile Erumen Lizard
- Tough Erumen Lizard
- Hardened Erumen Lizard

"Erume**m**" occurs 6 times in `monsterlist_v0611_monsters1.json` and `monsterlist_v070_lodarmaze.json` and doesn't occur in internal IDs:

- Young Erumem Lizard
- Spotted Erumem Lizard
- Erumem Lizard
- Young erumem forest lizard
- Erumem forest lizard
- Erumem forest lizard matriarch
- Erumen Lizard

The internal ID is "erume**n**". Are you sure that "erume**m**" is the correct name? It seems that it should be "erume**n**".

**Comment by Zukero** [comment]
Damerilias need a lowercase d indeed, except when used as the item name, or to begin a sentence.

**Comment by Rijackson** [comment]
Yes, you are right about Erumen and Erumem. The ID is erumen, so I guess we should switch all occurrences to that spelling. There are capitalization problems too. Hardened Erumen Lizard should be Hardened erumen Lizard.

**Comment by Zukero** [comment]
Why capitalize Lizard?

**Comment by Rijackson** [comment]
Sorry. Typo! Strong erumen lizard.

**Comment by urbalazs** [comment]
I found some other issues:

- We have both _venomscales_ and _venomscale_:
   `Venomscale scales`
   `Venomscale amulet`
   `Venomscale master`
   All other occurrences are _venomscales_. I think, we should write _venomscales_ everywhere, but `Venomscales scales` sounds strange. What do you think?
- There are some monsters in sentences with capital letters, for example:
   _Talion in Loneford told me that in order to be cured of my affliction, I will need to bring four parts to him. The parts that I will need are five bones, two pieces of animal hair, one **Irdegh** poison gland and one empty vial. Bones and fur can probably be found on some animal in the wilderness, and the poison gland can be found on one of the **Irdeghs** that have been spotted to the east._
   I think, we should write all monsters with lowercase letters, because now the names are lowercase in `monsterlist_*` files. What do you think?
- In file `AndorsTrail/res/raw/monsterlist_guynmart.json` at line 675 there is a hero who has no name:
   ```
   "id":"guynmart_hero",
   "name":"",
   "iconID":"char_hero:0",
   "unique":1,
   "monsterClass":"humanoid",
   "phraseID":"guynmart_hero_10"
   ```
   Why doesn't have this hero a name?

**Comment by Rijackson** [comment]
1) They should be consistent, and I think they should all be venomscale. Since they are inconsistent we are free to choose which one we prefer, and as you say, venomscales scales sounds weird.

2) Agreed.

3) It's there to allow the hero sprite to be placed on the top of the monument. There is some dialogue for that NPC: "$playername monument - not bad.". We don't want a name to show up there, because the hero's name is not known.

**Comment by Zukero** [comment]
1. Agreed overall. I know at one point Halvor asks for venomscales' scales, meaning scales coming from several venomscales snakes. Maybe there's a better way to ask for these. 

2. Agreed. 

3. This would be better using a key area. A "dynamic placeholder" sprite will handle the graphical side of things.

**Comment by urbalazs** [comment]
Fixed with https://github.com/Zukero/andors-trail/commit/1c7f081f18e8b894e087fcfda3ad7483592c321b.
