### ISSUE TITLE
Inconsistent usage of non-verbal communications

### ISSUE THREAD

**Issue by urbalazs** [Zukero/andors-trail#80]
Hello @Rijackson,

Now we have three different forms, if the hero lies:

- (Lie): 12 times
- (lie): 3 times
- [Lie]: 5 times

In general for all non-verbal happenings there are also two forms:

- (Something happens, that is non verbal.)
- [Something happens, that is non verbal.]

What do you think, that would be the best form?

**Comment by Zukero** [comment]
I like the square brackets best. Parenthesis can convey some meaning in something verbal.

**Comment by urbalazs** [comment]
I found something like this:

- Remgard. \*sigh\*. OK, I'll do it.

Should we deal with this kind of non-verbal activity the same as above? If so, then should I change to:

- Remgard. [Sigh.] OK, I'll do it.

**Comment by Rijackson** [comment]
If the player makes a sound that is not speaking then *Sound* is correct, e.g *Sigh*, *Cough*. If it is a description of something happening then in almost all cases it's currently (description), e.g. (The priest mumbles something you can't hear), (The dog runs across the road). 

There are places that do not adhere to that rule though (other than the square brackets). For example.

        "id":"sienn_pet",
        "message":"*Shriek!*\n(The creature looks up at you, showing all its teeth, while making a high-pitched piercing sound.)",
        "replies":[
            {
                "text":"There, there. Easy now.",
                "nextPhraseID":"X"
            },
            {
                "text":"*slowly back away*",
                "nextPhraseID":"X"
            }
        ]

IMO it should be (slowly back away). However, I have never seen this rule written, I just inferred it from existing content. Maybe we should use ** whenever the player does something, whether they make a sound or not. But then both (Lie) and [Lie] would be wrong. 

The problem with fixing these inconsistencies is that there is no way to do it except by going through every occurrence by hand, because context matters.

**Comment by urbalazs** [comment]
I found some documents:
- https://www.transcribe.com/transcription-jobs-online/style-guide/
- http://www.msvu.ca/site/media/msvu/GuideTranscribing.pdf
- http://support.onespace.com/training-resources/transcription-style-guide

Everywhere are used brackets for non verbal communication.

**Comment by urbalazs** [comment]
According to the documents above I suggest the following rules as general rules:
1. Use always brackets as indicate non verbal communications in conversations. The text inside the brackets starts a capital letter, and has no punctuation.
2. Don't use brackets or parentheses in other places

Examples for point 1:
The non verbal communication is something as the hero does things:
`[Lie] Yes, I am here to get you. Follow me.`

The non verbal communication is the part of the conversation as separate sentence:
`[Falothen teaches you the two-handed sword skill]`

The non verbal communication is an activity that the hero does instead of speaking:
`[Run away screaming]`

The non verbal communication is connected to the verbal communication. In this case it has to be put before or after the verbal communication and separate it with a new line:
`[Gold taken]\n`
`Very good. I will close my eyes now and count to 10.`

`On one hand, Lord Geomyr supports Crossglen with a lot of protection.\n`
`[Points to the soldiers in the hall]`

The non verbal communication is part of the verbal communication and happens in the same time. In this situation the non verbal communication is written lowercase letter and it is part of the sentence:
`I recently went in to that cave over there [points west], to check on our supplies. But apparently, the cave has been infested with rats.`

The NPC has a non verbal communication in its verbal communication, but after or before he says something:
`Remgard. [Sigh] OK, I'll do it.`
`Rincel? No, not that I can recall. Actually, we don't get many children in here. [Chuckle]`

Example for point 2:
This is not part of a conversation. It is displayed in a pop-up window, so no brackets or parentheses are needed, because no need to separate it from verbal communications:
Wrong: `(The tombstone contains writing in a language that you do not understand)`
Correct: `The tombstone contains writing in a language that you do not understand.`

What do you think about this? Of course, exceptions always can be.

Your previous example would be this:
```
    "id":"sienn_pet",
    "message":"Aaargh!\n[The creature looks up at you, showing all its teeth, while making a high-pitched piercing sound]",
    "replies":[
        {
            "text":"There, there. Easy now.",
            "nextPhraseID":"X"
        },
        {
            "text":"[Slowly back away]",
            "nextPhraseID":"X"
        }
    ]
```
"Aaargh!" is the sound that the creature is "saying". This is a verbal communication. After it there is an explanation about what happens. This is the non verbal communication.

**Comment by Zukero** [comment]
It'll be better to have this consistency, but maybe this is something we can postpone to after v0.7.2 is released.

**Comment by urbalazs** [comment]
Is there a release date for v0.7.2?
I'm working on this issue. I agree with Rijackson, that every change will have to be checked, there is no way to automatic find and replace.

Asterisks are also used as emphasis:
`No, you get out of *my* way!`
`Do you really think you can defeat *me*? Ha ha, this will be fun!`

What do you think about this kind of usage? Should we change to anything, should we remove or should we leave it as is? For example in [FreedroidRPG](http://www.freedroid.org/) BBCode is used for emphasis:
`No, you get out of [b]my[/b] way!`
`Do you really think you can defeat [b]me[/b]? Ha ha, this will be fun!`

For this the display system needs to be changed.

**Comment by urbalazs** [comment]
Fixed with https://github.com/Zukero/andors-trail/commit/29971092585b72b3601208b74add4f304623ad72.
