### ISSUE TITLE
Inconsistent usage of Blackwater Montain

### ISSUE THREAD

**Issue by urbalazs** [Zukero/andors-trail#82]
Hello @Rijackson

What is the correct spelling for _Blackwater Montain_?

- Blackwater Mountain: occurs 68 times
- Blackwater mountain: occurs 26 times

With _settlement_:

- Blackwater Mountain settlement: occurs 41 times
- Blackwater Mountain Settlement: occurs 1 time
- Blackwater mountain settlement: occurs 12 times

**Comment by Rijackson** [comment]
I think it should be Blackwater mountain. Blackwater is a real name, mountain is just a noun.

**Comment by Zukero** [comment]
Agreed: `Blackwater mountain` and `Blackwater mountain settlement` are the way to go.

**Comment by urbalazs** [comment]
Fixed with https://github.com/Zukero/andors-trail/commit/47e47f9804c58297cfe8cc6264c0f670db6a9f0d.
