### ISSUE TITLE
0.7.2 is not present in F-Droid

### ISSUE THREAD

**Issue by KOLANICH** [Zukero/andors-trail#92]

**Comment by urbalazs** [comment]
7.2 is not reseased yet.

**Comment by Rijackson** [comment]
Yes it is. It was released yesterday.

**Comment by Zukero** [comment]
The F-droid team build apps themselves, which is great, but I have some repo management to do before thay are able to do it. It will be done shortly.

**Comment by urbalazs** [comment]
> Yes it is. It was released yesterday.

Then please [tag it](https://github.com/Zukero/andors-trail/tags) and add to [releases](https://github.com/Zukero/andors-trail/releases). Not everyone is reading the forum.

**Comment by Zukero** [comment]
Done for both 0.7.2 and 0.7.3.
