### ISSUE TITLE
Cyrillic is not supported

### ISSUE THREAD

**Issue by ghost** [Zukero/andors-trail#93]
If you play with russian translation, the names of settlements on the map will be written
![screenshot_20181207-110242](https://user-images.githubusercontent.com/43142013/49635764-d7666480-fa11-11e8-88f7-495e14195b0f.png)
![screenshot_20181207-110246](https://user-images.githubusercontent.com/43142013/49635766-d7666480-fa11-11e8-821a-d4a8349adcef.png)

To solve this problem, you can change the file [worldmap_template](https://github.com/Zukero/andors-trail/blob/master/AndorsTrail/res/values/worldmap_template.xml)
charset=iso-8859-1 --> charset=utf-8

result:
![screenshot_20181207-111333](https://user-images.githubusercontent.com/43142013/49636123-b9e5ca80-fa12-11e8-9221-f865f8c3b3d4.png)
![screenshot_20181207-111336](https://user-images.githubusercontent.com/43142013/49636124-ba7e6100-fa12-11e8-9828-51fd441ac466.png)

**Comment by Zukero** [comment]
Good catch! Thanks.
Do you think you can make a pull-request with the fix?

**Comment by soloply** [comment]
@Zukero, No...

**Comment by ArxARV** [comment]
I can find the file, but when it opens, I see a lot of strange characters, and nothing like what you show ...?

**Comment by Zukero** [comment]
This file isn't meant to be opened as is. It is a template, processed by the game to display the worldmap. I understand the issue, and agree with the fix proposed by @soloply
I'll deal with it soon.

**Comment by ArxARV** [comment]
Thank you very much!



сб, 8 дек. 2018 г., 18:18 Zukero notifications@github.com:

**Comment by soloply** [comment]
> This file isn't meant to be opened as is. It is a template, processed by the game to display the worldmap. I understand the issue, and agree with the fix proposed by @soloply
> I'll deal with it soon.

This fix works only with a new game or deleting folder "worldmap"
and already generated maps in worldmap wrongly displayed

**Comment by Zukero** [comment]
Deleting the worldmap folder is a bad move. I have some tests to perform on the current fix, and I have a way to ensure that these are regenerated after the update if need be.
