### ISSUE TITLE
feature request: slightly safer save button

### ISSUE THREAD

**Issue by bjmgeek** [Zukero/andors-trail#94]
The other day, I accidentally overwrote a save file for a different character.  Please pop up a warning if the character name of the current game doesn't match the existing save file.

thanks!

**Comment by Zukero** [comment]
It exists already. Check the preferences from the main menu. You'll see an option called "Confirm overwriting saved games" that has enough options to cover your needs.

**Comment by bjmgeek** [comment]
great, thanks!
