### ISSUE TITLE
GPL v2 incompatibility with Android Support library

### ISSUE THREAD

**Issue by relan** [Zukero/andors-trail#95]
Andor's Trail code is under the GNU GPL v2, but it uses android-support-v4 library, which is under Apache 2.0. Those licenses are incompatible: https://www.gnu.org/licenses/license-list.html#apache2

GPL v3 _is_ compatible with Apache 2.0. Please clarify whether _GPL v2_ in the readme means _GPL v2 only_ or _GPL v2 or later_.

**Comment by Zukero** [comment]
It is v2 or later, as specified in the game's About->License screen.
Thanks for bringing this up, we'll clarify in other materials.

**Comment by sdevaney** [comment]
I am no lawyer and the following could be incorrect but doesn't that fall into the system library exception? Google themselves call it essential: 'Originally a single binary library for apps, the Android Support Library has evolved into a suite of libraries for app development. Many of these libraries are now a strongly recommended, if not essential, part of app development.' 

Also generally speaking it is my understanding software created with the use of other software is not seen as a derivative work of that other software, and so the licence obligations don't transfer.

**Comment by Zukero** [comment]
@sdevaney I'd say this argument would work if the lib was simply included from a build script (like Gradle). However, we currently redistribute it by including the jar in our repo and in our APK ourselves. The issue is thus valid IMHO.

**Comment by sdevaney** [comment]
Ah I see; after doing more research that makes a lot of sense and I agree with your reasoning.

**Comment by relan** [comment]
Updated F-Droid metadata in https://gitlab.com/fdroid/fdroiddata/commit/37a0338e63daa818c3fb231c259d8b2908ec3949.

Thanks!
