### ISSUE TITLE
Red X on map disappears after Remgard

### ISSUE THREAD

**Issue by bjmgeek** [Zukero/andors-trail#96]
At some point during my activities in the Remgard area, the red X disappeared from the map.

**Comment by Zukero** [comment]
Yes. We are aware of this issue, and will look into fixing it for the next version.

**Comment by Zukero** [comment]
Fixed in master. Some negative variable was injected into javascript, causing something like 'X = Y--Z;' to be evaluated, which failed. We now have 'X = Y-(-Z);'
